sonar.sources=.
sonar.tests=tests,e2e
sonar.test.inclusions=tests/**/*.ts,e2e/**/*.ts
sonar.exclusions=tests/**,e2e/**,scripts/**,coverage/**,dist/**,node_modules/**,vite.config.ts,vitest.config.ts
sonar.cpd.exclusions=tests/**,e2e/**
sonar.sourceEncoding=UTF-8
